security:
  oauth2:
    client:
      clientId: USER_BSC_APP
      clientSecret: 1234
      accessTokenUri: http://localhost:8080/auth-service/api/v.1/oauth-clients/user/me
      grant-type: client_credentials
      scope: server

server:
  servlet:
    context-path: /plan-accion
  port: 8083

feign:
  hystrix:
    enabled: true

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://bsc-evedisa-db-server.postgres.database.azure.com:5432/planAccionTenant
    username: postgres
    password: p1t4g0r4S

  servlet:
    multipart:
      enabled: true
staticresourceloader:
  fileLocation:
    path: file:/home/avances/subirArchivos
  docFileLocation:
    path: file:/home/avances/subirArchivos

api:
  base:
    url: /api/v.1
